name: grand_pet
description: A new Flutter project.

publish_to: 'none'
shared_preference:
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_slidable: 1.1.0
  flutter:
    sdk: flutter

  firebase_analytics:
  cloud_firestore:
  google_sign_in:
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.17.3+1
  provider: ^6.0.1
  local_auth:
  shared_preferences: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/